# Generated by Django 4.2.18 on 2026-04-09 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0004_instituteprivatelibraryaccess_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama (Local)')], max_length=50)),
                ('scope', models.CharField(choices=[('system', 'System Default'), ('institute', 'Institute Level'), ('user', 'User Personal')], default='system', max_length=20)),
                ('api_key', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('rate_limit', models.IntegerField(default=0)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='institutes.institute')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('name', 'scope', 'institute', 'user')},
            },
        ),
    ]
