# Generated by Django 4.2.18 on 2026-04-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view_institute", "View Institute Data"),
                            ("edit_institute", "Edit Institute Data"),
                            ("moderate_content", "Moderate Content"),
                            ("publish_content", "Publish Content"),
                            ("review_answers", "Review Q&A Answers"),
                            ("manage_scholars", "Manage Scholars"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True, help_text="e.g., Institute", max_length=100, null=True
                    ),
                ),
                ("resource_id", models.IntegerField(blank=True, null=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Automatic expiration date", null=True
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-granted_at"],
                "unique_together": {("user", "permission", "resource_type", "resource_id")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("register", "User Registration"),
                            ("upload", "Book Upload"),
                            ("delete", "Content Deletion"),
                            ("review", "Scholar Review"),
                            ("approve", "Content Approval"),
                            ("reject", "Content Rejection"),
                            ("export", "Data Export"),
                            ("admin_action", "Admin Action"),
                            ("permission_grant", "Permission Granted"),
                            ("permission_revoke", "Permission Revoked"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(help_text="Model name (e.g., Book, Scholar)", max_length=100),
                ),
                ("resource_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("old_values", models.JSONField(blank=True, help_text="Previous state", null=True)),
                ("new_values", models.JSONField(blank=True, help_text="New state", null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="common_audi_user_id_efb617_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"], name="common_audi_action_ead800_idx"
                    ),
                ],
            },
        ),
    ]
