# Generated by Django 4.2.18 on 2026-04-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("library", "0001_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_engine_output", models.JSONField(blank=True, default=dict)),
                ("direct_answer", models.TextField(blank=True)),
                ("detailed_explanation", models.TextField(blank=True)),
                ("simplified_explanation", models.TextField(blank=True)),
                ("generated_examples", models.JSONField(blank=True, default=list)),
                ("optional_exercises", models.JSONField(blank=True, default=list)),
                ("scholar_reviews_snapshot", models.JSONField(blank=True, default=list)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("source_grounded", "Source Grounded"),
                            ("scholar_verified", "Scholar Verified"),
                            ("disputed", "Disputed"),
                            ("ai_summary_only", "AI Summary Only"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="needs_review",
                        max_length=30,
                    ),
                ),
                ("confidence", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("related_topics", models.JSONField(blank=True, default=list)),
                ("answer_provenance", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RetrievedSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("score", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("retrieval_reason", models.CharField(blank=True, max_length=255)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrieved_sources",
                        to="qa_engine.answer",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_hits",
                        to="library.book",
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retrieval_hits",
                        to="library.bookchunk",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuotedPassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quoted_text", models.TextField()),
                ("snippet", models.TextField(blank=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quoted_passages",
                        to="qa_engine.answer",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quoted_passages",
                        to="qa_engine.retrievedsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("language_pair", models.CharField(default="ar-en", max_length=50)),
                ("detected_subject", models.CharField(blank=True, max_length=255)),
                ("detected_sub_subject", models.CharField(blank=True, max_length=255)),
                ("detected_intent", models.CharField(blank=True, max_length=255)),
                ("detected_level", models.CharField(blank=True, max_length=100)),
                ("sensitivity_level", models.CharField(default="normal", max_length=50)),
                ("search_scope", models.CharField(default="general", max_length=50)),
                ("verification_preference", models.CharField(default="default", max_length=50)),
                ("response", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="qa_engine.query",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="selected_skill_pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers",
                to="skills.skillpack",
            ),
        ),
    ]
