# Generated by Django 4.2.18 on 2026-04-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institutes", "0002_auto_20260408_1028"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituteMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "Platform Admin"),
                            ("institute_admin", "Institute Admin"),
                            ("scholar", "Scholar"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("reviewer", "Reviewer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstitutePrivateLibraryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[("view", "View"), ("study", "Study"), ("manage", "Manage")],
                        default="view",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="classdarjah",
            options={},
        ),
        migrations.AddField(
            model_name="classdarjah",
            name="code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="classdarjah",
            name="language_pair",
            field=models.CharField(
                choices=[("ar-ur", "Arabic + Urdu"), ("ar-en", "Arabic + English")],
                default="ar-en",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="classdarjah",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="classdarjah",
            name="order_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="classdarjah",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="institute",
            name="branding",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="institute",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institute",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="institute",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="institute",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="institute",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="arabic_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="classdarjah",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="institutes.institute",
            ),
        ),
        migrations.AlterField(
            model_name="classdarjah",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="institute",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_institutes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classdarjah",
            unique_together={("institute", "name")},
        ),
        migrations.CreateModel(
            name="InstituteSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("curriculum_metadata", models.JSONField(default=dict)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "class_darjah",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_offerings",
                        to="institutes.classdarjah",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_offerings",
                        to="institutes.institute",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institute_offerings",
                        to="institutes.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
