# Generated by Django 4.2.18 on 2026-04-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institutes", "0003_institutemembership_instituteprivatelibraryaccess_and_more"),
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instituteprivatelibraryaccess",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_access_entries",
                to="library.book",
            ),
        ),
        migrations.AddField(
            model_name="instituteprivatelibraryaccess",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_library_access_entries",
                to="institutes.institute",
            ),
        ),
        migrations.AddField(
            model_name="institutemembership",
            name="class_darjah",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberships",
                to="institutes.classdarjah",
            ),
        ),
        migrations.AddField(
            model_name="institutemembership",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="institutes.institute",
            ),
        ),
        migrations.AddField(
            model_name="institutemembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="institutemembership",
            unique_together={("user", "institute", "role")},
        ),
    ]
