# Generated by Django 4.2.18 on 2026-04-09 08:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('institutes', '0004_instituteprivatelibraryaccess_book_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(choices=[('topic', 'Topic'), ('concept', 'Concept'), ('rule', 'Rule'), ('example', 'Example'), ('definition', 'Definition')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_objects', to='library.book')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_objects', to='library.bookchunk')),
                ('skill_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_objects', to='skills.skillpack')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_objects', to='institutes.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
