# Generated by Django 4.2.18 on 2026-04-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="class_darjah",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="institutes.classdarjah",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="institute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="institutes.institute",
            ),
        ),
    ]
