# Generated by Django 4.2.18 on 2026-04-09

import apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_public_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.managers.CustomUserManager()),
            ],
        ),
    ]
