# Generated by Django 4.2.18 on 2026-04-08 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("sub_subject", models.CharField(blank=True, max_length=255)),
                ("level", models.CharField(blank=True, max_length=50)),
                ("answer_template", models.JSONField(blank=True, default=dict)),
                ("retrieval_rules", models.JSONField(blank=True, default=dict)),
                ("citation_rules", models.JSONField(blank=True, default=dict)),
                ("repeat_matan_policy", models.JSONField(blank=True, default=dict)),
                ("summary_policy", models.JSONField(blank=True, default=dict)),
                ("comparison_policy", models.JSONField(blank=True, default=dict)),
                ("conflict_handling_policy", models.JSONField(blank=True, default=dict)),
                ("scholar_priority_policy", models.JSONField(blank=True, default=dict)),
                ("exercise_generation_policy", models.JSONField(blank=True, default=dict)),
                ("language_style", models.JSONField(blank=True, default=dict)),
                ("verification_requirements", models.JSONField(blank=True, default=dict)),
                ("sensitivity_policy", models.JSONField(blank=True, default=dict)),
                ("rules", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "source_books",
                    models.ManyToManyField(
                        blank=True, related_name="skill_packs", to="library.book"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
