# Generated by Django 4.2.18 on 2026-04-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("library", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadsession",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_sessions",
                to="library.book",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upload_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ingestionstagerun",
            name="upload_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stage_runs",
                to="ingestion.uploadsession",
            ),
        ),
    ]
