# Generated by Django 4.2.18 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("uploaded", "Uploaded"),
                    ("metadata_pending", "Metadata Pending"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("review_pending", "Review Pending"),
                    ("published", "Published"),
                    ("failed", "Failed"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
